### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by vitosnatios** [Leoff00/gofastypo#4]
Hello, @Leoff00. I've brought a list of improvement suggestions that may overall make the app better.

`Start! button`
- Pressing the "Start!" more than 2 times will make the timer to run faster, so, the button or/and it's function should be disabled by pressing it once.

`Stop! button`
- If you press the 'Stop!' button immediately after opening the app, it will freeze the application, preventing the user from clicking anywhere else. To address this issue, the button should be disabled by default and remain disabled whenever the timer isn't running.

`words/minute counter`
- It should pause its own current state after the user presses the "Stop!" button or whenever the timer runs out.

`Select the minutage`
- The "Start!" button and/or its function should be disabled while the user hasn't choose the duration.

**Comment by Leoff00** [comment]
All suggestestions were adjusted.
